version: 53
jobs:
- name: CI
  jobExecutor: LDY-executor
  steps:
  - type: CheckoutStep
    name: CheckoutStep
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: Build
    runInContainer: true
    image: golang
    interpreter:
      type: PosixInterpreter
      shell: sh
      commands: |
        go build -o puta .
    runAs: 0:0
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: main
    paths: -.onedev-buildspec.yml
    userMatch: anyone
    projects: LdyPage/puta
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  includeUpstreamWhenRebuild: false
  includeDownstreamWhenRebuild: false
  timeout: 14400
