version: 53
jobs:
- name: CI
  jobExecutor: LDY-shell-executor
  steps:
  - type: CommandStep
    name: Deploy
    runInContainer: false
    interpreter:
      type: PosixInterpreter
      shell: sh
      commands: "if [ -d \"/home/admin/webroot/puta\" ]; then \n\tgit pull\n\t\nelse\n\tgit clone ssh://hulutv.vip:6611/LdyPage/puta.git /home/admin/webroot\n\tgit pull\nfi\n"
    runAs: 0:0
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: main
    paths: -.onedev-buildspec.yml
    userMatch: anyone
    projects: LdyPage/puta
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  includeUpstreamWhenRebuild: false
  includeDownstreamWhenRebuild: false
  timeout: 14400
